# Generated by Django 4.2.11 on 2024-05-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Содержимое заказа', 'verbose_name_plural': 'Содержимое заказа'},
        ),
    ]
