# Generated by Django 4.2.11 on 2024-05-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(choices=[(False, 'Недоступен'), (True, 'Доступен')], default=0, verbose_name='Статус'),
        ),
    ]
